version: "3.9"
services:
  shinyproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: naturecons/shinyproxy
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
      - ./application.yml:/opt/shinyproxy/application.yml
      - ./shinyproxy-3.0.2.jar:/opt/shinyproxy/shinyproxy.jar

networks:
  net:
    name: net
